### ISSUE TITLE
PushToTalk with XButton1

### ISSUE THREAD

**Issue by MidnightDemon** [YoYo-Pete/AutoHotKeys#1]
Just wondering how to modify this to work with mouse buttons. Thank you!

**Comment by Doshin108** [comment]
Hey... Sorry I missed the notification from this.

Line 38...Change Capslock to XButton1

`$Capslock:: ;Change this for the button you want to use`
change to 
`$XButton1: ;Change this for the button you want to use`

Here's the list of 'other' keys if you want to modify it differently: https://autohotkey.com/docs/KeyList.htm

**Comment by Doshin108** [comment]
Feel free to reopen or make a new issue if that didnt get you what you need.
